name: RADIO
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - appdirs=1.4.4
  - atomicwrites=1.4.0
  - attrs=21.4.0
  - black=19.10b0
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - colorama=0.4.4
  - coverage=5.5
  - coveralls=3.2.0
  - cpuonly=2.0
  - cryptography=36.0.0
  - cudatoolkit=11.5.0
  - cudnn=8.2.1.32
  - docopt=0.6.2
  - flake8=4.0.1
  - freetype=2.10.4
  - future=0.18.2
  - idna=3.3
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - jpeg=9d
  - libpng=1.6.37
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp=1.2.0
  - lz4-c=1.9.3
  - mccabe=0.6.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - more-itertools=8.12.0
  - mypy_extensions=0.4.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openssl=1.1.1m
  - packaging=21.3
  - pathlib2=2.3.6
  - pathspec=0.7.0
  - pip=21.2.4
  - pluggy=0.13.1
  - py=1.10.0
  - pycodestyle=2.7.0
  - pycparser=2.21
  - pyflakes=2.3.1
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - pytest=6.2.4
  - pytest-cov=3.0.0
  - python=3.9.7
  - pytorch=1.10.1
  - pytorch-mutex=1.0
  - pyyaml=6.0
  - regex=2021.8.3
  - requests=2.27.1
  - rope=0.21.1
  - six=1.16.0
  - sqlite=3.37.0
  - tk=8.6.11
  - toml=0.10.2
  - torchvision=0.11.2
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - urllib3=1.26.8
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - alembic==1.7.5
    - antlr4-python3-runtime==4.8
    - anyio==3.5.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - argparse==1.4.0
    - astroid==2.9.3
    - asttokens==2.0.5
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - autoflake==1.4
    - autoimport==1.0.4
    - babel==2.9.1
    - backcall==0.2.0
    - batchgenerators==0.23
    - beautifulsoup4==4.10.0
    - bleach==4.1.0
    - cachetools==5.0.0
    - cloudpickle==2.0.0
    - colorlog==6.6.0
    - cycler==0.11.0
    - databricks-cli==0.16.2
    - debugpy==1.5.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - deprecated==1.2.13
    - docker==5.0.3
    - dominate==2.6.0
    - einops==0.4.0
    - entrypoints==0.3
    - executing==0.8.2
    - filelock==3.4.2
    - flask==2.0.2
    - flatbuffers==1.12
    - fonttools==4.29.0
    - frozenlist==1.3.0
    - fsspec==2022.1.0
    - gast==0.4.0
    - gdown==4.2.1
    - gitdb==4.0.9
    - gitpython==3.1.26
    - google-auth==2.6.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - gputil==1.4.0
    - greenlet==1.1.2
    - grpcio==1.43.0
    - h5py==3.7.0
    - huggingface-hub==0.4.0
    - humanize==3.14.0
    - hydra-colorlog==1.1.0
    - hydra-core==1.1.1
    - hydra-submitit-launcher==1.1.6
    - imagecodecs==2021.11.20
    - imageio==2.14.1
    - importlib-metadata==4.10.1
    - ipykernel==6.7.0
    - ipython==8.0.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - isort==5.10.1
    - itk==5.2.1.post1
    - itk-core==5.2.1.post1
    - itk-filtering==5.2.1.post1
    - itk-io==5.2.1.post1
    - itk-numerics==5.2.1.post1
    - itk-registration==5.2.1.post1
    - itk-segmentation==5.2.1.post1
    - itsdangerous==2.0.1
    - jedi==0.18.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - json5==0.9.6
    - jsonpatch==1.32
    - jsonpointer==2.2
    - jsonschema==4.4.0
    - jupyter-client==7.1.2
    - jupyter-core==4.9.1
    - jupyter-server==1.13.4
    - jupyterlab==3.2.8
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.10.3
    - jupyterlab-vim==0.14.5
    - jupyterlab-widgets==1.0.2
    - jupytext==1.13.6
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - lazy-object-proxy==1.7.1
    - libclang==14.0.1
    - linecache2==1.0.0
    - lmdb==1.3.0
    - maison==1.3.0
    - mako==1.1.6
    - markdown==3.3.6
    - markdown-it-py==1.1.0
    - markupsafe==2.0.1
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mdit-py-plugins==0.3.0
    - mistune==0.8.4
    - mlflow==1.23.1
    - monai==0.8.0
    - multidict==6.0.2
    - mypy==0.931
    - nbclassic==0.3.5
    - nbclient==0.5.10
    - nbconvert==6.4.1
    - nbformat==5.1.3
    - nest-asyncio==1.5.4
    - networkx==2.6.3
    - nibabel==3.2.1
    - notebook==6.4.8
    - oauthlib==3.2.0
    - omegaconf==2.1.1
    - openslide-python==1.1.2
    - opt-einsum==3.3.0
    - pandas==1.4.0
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pdoc3==0.10.0
    - pickleshare==0.7.5
    - pillow==9.0.0
    - platformdirs==2.4.1
    - prometheus-client==0.13.1
    - prometheus-flask-exporter==0.18.7
    - prompt-toolkit==3.0.26
    - protobuf==3.19.4
    - psutil==5.9.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.9.0
    - pydeprecate==0.3.1
    - pygments==2.11.2
    - pylint==2.12.2
    - pyprojroot==0.2.0
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytorch-ignite==0.4.8
    - pytorch-lightning==1.5.9
    - pytz==2021.3
    - pywavelets==1.2.0
    - pywin32==227
    - pywinpty==2.0.1
    - pyzmq==22.3.0
    - querystring-parser==1.2.4
    - radio==1.1.dev0
    - requests-oauthlib==1.3.1
    - rising==0.2.2
    - rsa==4.8
    - sacremoses==0.0.47
    - scikit-image==0.19.1
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.11.2
    - send2trash==1.8.0
    - setuptools==59.5.0
    - sh==1.14.2
    - simpleitk==2.1.1
    - smmap==5.0.0
    - sniffio==1.2.0
    - soupsieve==2.3.1
    - sqlalchemy==1.4.31
    - sqlparse==0.4.2
    - stack-data==0.1.4
    - submitit==1.4.1
    - tabulate==0.8.9
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.4.1
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - terminado==0.13.1
    - testpath==0.5.0
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - tokenizers==0.11.4
    - tomli==2.0.0
    - torchfile==0.1.0
    - torchio==0.18.73
    - torchmetrics==0.7.0
    - tornado==6.1
    - tqdm==4.62.3
    - traceback2==1.4.0
    - traitlets==5.1.1
    - transformers==4.16.2
    - types-pillow==9.0.5
    - types-requests==2.27.8
    - types-urllib3==1.26.8
    - unittest2==1.1.0
    - visdom==0.1.8.9
    - waitress==2.0.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.2.3
    - werkzeug==2.0.2
    - widgetsnbextension==3.5.2
    - wrapt==1.13.3
    - yapf==0.32.0
    - yarl==1.7.2
    - zipp==3.7.0
