---
title: "mprage-file-processing"
author: "Anzu Sekikawa"
date: '2022-08-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tibble)
library(tidyverse)
library(dplyr)
```


```{r}



```

```{r}


raw <- read.csv("mp-rage-files.txt", sep="/", header=FALSE)

raw$V7 <- rep( "ADNIPET", each=nrow(t))

raw$V8 <- rep("MRI_PIB", each=nrow(t))

raw <- t[,c("V7","V8","V1","V2","V3","V4","V5","V6") ]

#View(path_names)
  
raw <- raw %>% 
  rename(
    "ADNIPET" = V7,
    "MRI_PIB" = V8,
    "ADNI" = V1,
    "PTID"=V2,
    "MP-RAGE" = V3,
    "mprage_date" = V4,
    "mprage_num" = V5,
    "mprage_filename" = V6
  )



raw_uniq <- raw %>% distinct(PTID, .keep_all=TRUE)


mprage_full_path <- raw_uniq %>%
  unite('full_path', sep="/")


#write.csv(mprage_full_path, file="mprage-paths.txt", quote=FALSE,row.names=FALSE)



names(mprage_full_path)


raw_uniq$MPRAGE_FULL_PATH <- mprage_full_path$full_path

View(raw_uniq)

mprage_df <- raw_uniq[, c(4,6,7,8,9)]

#View(mprage_df)

#write.csv(mprage_df, file="mprage_df.csv", row.names=FALSE)



```

```{r}

```

